[package]
name = "transg"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "transg"
path = "src/main.rs"



[dependencies]
gtk = { version = "0.4.7", package = "gtk4", features = ["v4_4"]}
once_cell = "1.5"
transmission-rpc = "0.3.6"
tokio = { version = "1.18.0", features = ["full"]}


[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"
